name: maven build
on:
  push:
    branches: [ emre ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' 
          java-version: '11'
      - run: java -cp java forexRateConmverterApp
